config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  resources :users do
    get 'activate_tour_guide', to: 'users#activate_tour_guide'
  end
  resources :sessions
  resources :searchs
  resources :contracts do
    post 'confirmation', to: 'contracts#confirmation'
    get 'accepted', to: 'contracts#accepted'
  end

  get 'request_notification', to: 'contracts#request_notification'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  post '/nearby_guides' => 'searchs#nearby_guides'
  post '/single_person' => 'searchs#single_person'
  

end

app/models/contract.rb
class Contract < ActiveRecord::Base

belongs_to :contractor, class_name: "User", foreign_key: :contractor_id, inverse_of: :contractors
belongs_to :contractee, class_name: "User", foreign_key: :contractee_id, inverse_of: :contractees

end

app/models/search.rb
class Search < ActiveRecord::Base

	
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
has_many :contractors, class_name: "Contract", foreign_key: :contractor_id, inverse_of: :contractor
has_many :contractees, class_name: "Contract", foreign_key: :contractee_id, inverse_of: :contractee

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
  
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

	def single_person
		user = User.find(params[:user_id])
		user_id = user.id
		render :js => "window.location = #{new_contract_path(:user => user_id).to_json}"
	end	


	def create
		@contract = Contract.new(params.require(:contract).permit(:contractor_id, :contractee_id, :confirmation))
		@contract.save
		redirect_to contracts_path
	end


	def index
		 @contracts = Contract.where('contractor_id = ? OR contractee_id = ?', current_user, current_user)
	end


	def request_notification
		@contracts = Contract.where('contractee_id =? AND confirmation = ?', params[:current_user], false)
	end


	def confirmation
		contract = Contract.find(params[:contract_id])
		contract.confirmation = true
		contract.save
		redirect_to searchs_new_path
	end


	def show
		@contract = Contract.find(params[:contract_id])
	end

	def accepted
		@contractor = Contract.where('contractor_id = ? AND confirmation = ?', params[:contract_id], true )
		@contractee = Contract.where('contractee_id = ? AND confirmation = ?', params[:contract_id], true )
	end



end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

	def new
		@current_user = User.find(params[:user_id])
		@tour_guide = @current_user.tour_guide
	end

	def nearby_guides
		@address = params[:address]
		initial_array = @address.split(',')
		city = initial_array[0]
		state = initial_array[1].split(' ')
		final_state = state[0]
		country = initial_array[2].split(' ')
		final_country = country[0]
		@result = User.where("city = ? AND state = ? AND country = ? AND tour_guide = ?", city, final_state, final_country, true)
		respond_to do |format|	
			format.json { render :json => @result }
	    	format.html { render 'nearby_guides' }
		end
	end

	def single_person
		user = User.find(params[:user_id])
		user_id = user.id
		render :js => "window.location = #{search_path(:id => user_id).to_json}"
	end

	def show
		user = params[:id]
		@user = User.where(id: user).to_a
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to new_search_path(:user_id => user.id)
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	  def new
    end

    def create
    	user = User.new(user_params)
    	if user.save
      		session[:user_id] = user.id
      		redirect_to '/'
    	else
      		redirect_to '/signup'
    	end
    end  

    def activate_tour_guide
      user = User.find(params[:user_id])
      tour_guide = user.tour_guide
      if tour_guide
        user.tour_guide = false
        user.save
        redirect_to new_search_path(:user_id => user.id)
      else
        user.tour_guide = true 
        user.save
        redirect_to new_search_path(:user_id => user.id)
      end
    end 

    private

  	def user_params
    	params.require(:user).permit(:firstname, :email, :lastname, :bio, :city, :state, :country, :password, :password_confirmation, :tour_guide)
  	end


	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contracts/accepted.html.erb
<h2> Accepted Contracts </h2>


<h3> People taking you around </h3>
<% if @contractor.exists? %>

<% @contractor.each do |contract| %>
	<h4>Your Tour Guide:</h4> <% User.where(id: contract.contractee_id).each do |user| %>
		<%= user.firstname %> 
		<%= user.lastname %>
		<%= user.bio %>
		<% end %>
	<% end %>
<% else %>
<h3> You have no contracts </h3>
<% end %>


<h3> People you are taking around </h3>
<% if @contractee.exists? %>
<% @contractee.each do |contract| %>
	<h4>Your Visitor:</h4> <% User.where(id: contract.contractor_id).each do |user| %>
		<%= user.firstname %> 
		<%= user.lastname %>
		<%= user.bio %>
		<% end %>
	<% end %>
<% else %>
<h3> You have no contracts </h3>
<% end %>

app/views/contracts/index.html.erb
<h2> Pending Contracts </h2>

<% @contracts. each do |contract|%>
	<h4>Tour Guide:</h4> <% User.where(id: contract.contractee_id).each do |user| %>
		<%= user.firstname %> 
		<%= user.lastname %>
		<%= user.bio %>
		<% end %>

	<h4>Visitor:</h4> <% User.where(id: contract.contractor_id).each do |user| %>
		<%= user.firstname %> 
		<%= user.lastname %>
		<% end %>



	<% if current_user.id == contract.contractee_id %>
		<%= form_for(:contract, :url => url_for(:controller => 'contracts', :action => 'confirmation')) do |f| %>
        <%= f.hidden_field :contract_id, value: @contract.id %>
        <%= f.submit "Accept the Tour Request" %>
		<% end %>
	<% end %>






<% end %>

app/views/contracts/request_notification.html.erb
<h1>Contracts wating for your confirmation</h1>

<% @contracts.each do |c| %>

	<% User.where(id: c.contractor_id).each do |p| %>
		<%= p.firstname %>
		<%= p.lastname %>
	<% end %>
	
<%= form_for :contract, :url => contract_confirmation_path(:contract_id => c.id) do |f| %>		
        <%= f.hidden_field :contract_id, value: c.id %>
        <%= f.submit "Accept the Tour Request" %>
		<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Tourio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "vendor/modernizr"
%>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searchs/_nav.html.erb
<%= link_to "Logout", '/logout' %>

<% if Contract.exists?(:contractee_id=>@current_user.id, :confirmation=>false)  %>
<%= link_to "You have a pending contract", request_notification_path(:current_user => @current_user.id) %>
<% end %>


<% if @current_user.tour_guide == false %>
	<%= form_tag user_activate_tour_guide_path(:user_id => @current_user.id), method: :get do  %>
	  	<%= submit_tag 'Turn On Tour Guide' %>
	<% end %>
<% end %>

<% if @current_user.tour_guide == true %>
	<%= form_tag user_activate_tour_guide_path(:user_id => @current_user.id), method: :get do  %>
	  	<%= submit_tag 'Tour off Tour Guide' %>
	<% end %>
<% end %>

<%= link_to "Accepted Contracts", contract_accepted_path(:contract_id =>@current_user.id) %>

app/views/searchs/_result.html.erb
<h1> HELLO WORLD </h1>

<% if @result %>
<% @result.each do |result| %>
<%= result.firstname %>
<% end %>
<% end %>

app/views/searchs/new.html.erb
<%= render 'nav' %>

<%= render 'result' %>

<h1>Welcome to no paid tour guide app</h1>

<p>Welcome:</p>
<%= @current_user.firstname %> <%= @current_user.lastname %>

<% if @tour_guide %>
  <p>You are now a tour guide.</p>
<% end %>

<% if @tour_guide == false %>
  <p>You are currently not a tour guide.</p>
<% end %> 

<div id='demo'></div>

<input type="submit" value="Your coordinates" onclick=getLocation()>

<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5E_WnVSBNz5it07jKXOsoKdSlSOdtiB0">
</script>

<script>

document.onload = function initialize() {
    var geocoder = new google.maps.Geocoder();
    }

var x = document.getElementById("demo");
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function codeLatLng(latitude, longitude){
	var geocoder = new google.maps.Geocoder();
	var latlng = new google.maps.LatLng(latitude, longitude);
    geocoder.geocode({'latLng': latlng}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
      	var locationInfo = document.getElementById("demo");
      	locationInfo.innerHTML=results[4].formatted_address;
        var address = results[4].formatted_address;
        delivery(address);
      } else {
        alert("Geocoder failed due to: " + status);
      }
    });
}

function showPosition(position) {
    var latitude = position.coords.latitude;
    var longitude = position.coords.longitude; 
    codeLatLng(latitude, longitude);
}

function delivery(address){
$.ajax({
    type: "POST",
    url: "/nearby_guides",
    data: "address=" + address,
    success: function (json){
      console.log("ajax sent");
    for (var i = 0; i <= json.length - 1; i++) {

      newdiv = document.createElement('div');
      divClassName = 'result';
      newdiv.setAttribute('class',divClassName);
      newdiv.innerHTML = json[i].firstname;
      document.body.appendChild(newdiv);

      newdiv = document.createElement('div');
      divClassName = 'result';
      newdiv.setAttribute('class',divClassName);
      newdiv.innerHTML = json[i].lastname;
      document.body.appendChild(newdiv);

      newdiv = document.createElement('div');
      divClassName = 'result';
      newdiv.setAttribute('class',divClassName);
      newdiv.innerHTML = json[i].bio;
      document.body.appendChild(newdiv);

      newdiv = document.createElement('div');
      divClassName = 'result';
      newdiv.setAttribute('class',divClassName);
      newdiv.innerHTML = "<a href='#' onclick=showUser(" + json[i].id + ")>click</a>";
      document.body.appendChild(newdiv);

      }   
    },
    failure: function(){
      console.log("ajax failed");
    },
    dataType: "json"
  });
}

function showUser(id) {
  $.ajax({
    type: "POST",
    url: "/single_person",
    data: "user_id=" + id,
    success: function(json) {
      console.log('received');
    },
    failure: function() {
      console.og('fail');
    } 
  });
}

</script>
<div id='text'></div>

app/views/searchs/show.html.erb
<h1>The Person You Picked</h1>

First Name: <%= @user[0].firstname %></br>
Last Name: <%= @user[0].lastname %></br>
Bio: <%= @user[0].bio %>


<%= form_for(:contract, :url => url_for(:controller => 'contracts', :action => 'create')) do |f| %>
	<%= f.hidden_field :contractor_id, value: current_user.id %>
	<%= f.hidden_field :contractee_id, value: @user[0].id %>
	<%= f.hidden_field :confirmation, value: false %>
	<%= f.submit "Request Tour" %>
<% end %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %> 
  <%= f.password_field :password %>

  <%= f.label :password_confirmation%> 
  <%= f.password_field :password_confirmation %>

  <%= f.label :firstname %>
  <%= f.text_field :firstname %>

  <%= f.label :lastname%>
  <%= f.text_field :lastname %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :country %>
  <%= f.text_field :country %>

  <%= f.label :bio %>
  <%= f.text_field :bio %>

  <%= f.hidden_field :tour_guide, value: false %>

  <%= f.submit "Submit" %>

<% end %>

<%= link_to "Back", new_session_path %>